services:
  postgres_db:
    image: postgres:15-alpine
    container_name: cinema_postgres
    environment:
      POSTGRES_USER: cinema_admin
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: cinema_booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_db/init:/docker-entrypoint-initdb.d
    networks:
      - cinema_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinema_admin -d cinema_booking"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: cinema_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cinebook.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/tmp/pgpass_temp
    networks:
      - cinema_network
    depends_on:
      - postgres_db
    entrypoint: >
      /bin/sh -c "
        mkdir -p -m 700 /var/lib/pgadmin/storage/admin_cinebook.com;
        cp /tmp/pgpass_temp /var/lib/pgadmin/storage/admin_cinebook.com/pgpass;
        sed -i 's/\r$//' /var/lib/pgadmin/storage/admin_cinebook.com/pgpass;
        chmod 600 /var/lib/pgadmin/storage/admin_cinebook.com/pgpass;
        chown -R 5050:5050 /var/lib/pgadmin/storage/admin_cinebook.com;
        /entrypoint.sh
      "

  server:
    build:
      context: ./source/admin/server
    container_name: cinema_server
    ports:
      - "3000:3000"
    environment:
      PORT: 3000

      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: cinema_admin
      DB_PASSWORD: securepassword123
      DB_NAME: cinema_booking
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - cinema_network
    volumes:
      - ./source/admin/server:/app
    restart: unless-stopped

  client:
    build:
      context: ./source/admin/client
    container_name: cinema_client
    ports:
      - "5173:5173"
    environment:
      PORT: 5173
      API_URL: http://server:3000/api/v1
    networks:
      - cinema_network
    volumes:
      - ./source/admin/server:/app
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  cinema_network:
    driver: bridge
